// Auto-generated by scripts/migrate-data.mjs
// Do not edit manually — edit per-flavor files in ./flavors/ instead.

import type { Publisher } from './types'

// OCP-compliant auto-discovery: a new flavor file in ./flavors/ is
// automatically included in the registry without code edits here.
const modules = import.meta.glob('./flavors/*.ts', { eager: true, import: 'default' }) as Record<string, Publisher>

export const publishers: Publisher[] = Object.values(modules)
  .sort((a, b) => a.flavor.localeCompare(b.flavor))

export const publishersByFlavor = new Map(publishers.map(p => [p.flavor, p]))

export function getPublisher(flavor: string): Publisher | undefined {
  return publishersByFlavor.get(flavor)
}

export function getPublishersByCategory(category: Publisher['category']): Publisher[] {
  return publishers.filter(p => p.category === category)
}

export const internationalPublishers = getPublishersByCategory('international')
export const regionalPublishers = getPublishersByCategory('regional')
export const nationalPublishers = getPublishersByCategory('national')
export const industryPublishers = getPublishersByCategory('industry')
